---
title: "Lab 00 - Hello IDS!"
author: "Saleh Mammadzada"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Noah", "Nihad", "Dominik", 
           "Chanji", "Tommy"),
  github_username = c("ZiyeYang","Nihad457", "Dominiklaska8", 
                      "username 3", "Tommy-Rollins"), 
  colour = c("green", "white", "purple", 
             "blue", "purple"),
  hobby = c("painting", "reading", "reading", 
            "watching movies", "running"),
  favourite_number = c(7, 5 , 8 , 7, 3)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

favourite numbers

